#program to exibit different operations(sum , sub, multiply ...)
a = int(input("enter first number :"))
b = int(input("enter second number :"))
print("sum is : ",a+b)
print("sub is : ",a-b)
print("multiply is : ",a*b)
print("divide is : ",a/b)   
print("modulus is : ",a%b)
print("exponent is : ",a**b)
print("increment is : ",a+1)
print("decrement is : ",a-1)
